routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// -- Authentication Routes
Auth::routes();

// -- BEGIN -- public routes
Route::get('/', function () {
    return view('welcome');
});

Route::get('logout', function () {
    Auth::logout();
    session()->flush();
    return redirect('/');
});

Route::get('home', function () {
    return redirect()->route('dashboard.index');
});
// -- END -- Public routes

// -- BEGIN -- Private route
Route::middleware('auth')->group(function () {
    // -- BEGIN -- Resource route
    Route::resource('dashboard', 'DashboardController', ['only' => ['index']]);
    Route::middleware('RoleAuth:App\User')
        ->resource('users', 'UsersController', ['except' => ['show']]);
    Route::middleware('RoleAuth:App\Module')
        ->resource('modules', 'ModulesController');
    Route::middleware('RoleAuth:App\Staff')
        ->resource('staffs', 'StaffsController');
    Route::middleware('RoleAuth:App\Rolegroup')
        ->resource('rolegroups', 'RolegroupsController', ['except' => ['show']]);
    // -- END -- Resource binding

    // -- BEGIN -- Datatables Specific
    Route::group(['prefix' => 'datatables'], function () {
        Route::post('users', 'DatatablesController@users')
            ->name('datatables.users');
        Route::post('rolegroups', 'DatatablesController@rolegroups')
            ->name('datatables.rolegroups');
        Route::post('modules', 'DatatablesController@modules')
            ->name('datatables.modules');
    });
    // -- END -- Datatables Specific

    // -- BEGIN -- Other API Router
    Route::post('rolegroups/add_modules/{id}', 'RolegroupsController@addModules')
        ->name('rolegroups.addModules');
    Route::post('rolegroups/remove_modules/{id}', 'RolegroupsController@removeModules')
        ->name('rolegroups.removeModules');
    // -- END -- Other API Router
});
// -- END -- Model binding

app/Staff.php
<?php

namespace App;

use App\BaseModel as Model;

class Staff extends Model
{
    protected $table = 'staffs';

    protected $fillable = [
        'name', 'user_id'
    ];

    public $moduleName = 'Staff';

    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/StaffsController.php
<?php

namespace App\Http\Controllers;

use App\Staff;
use Illuminate\Http\Request;

class StaffsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $staffs = Staffs::all();
        return view('staffs.index')->with(['staffs' => $staffs]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Staff  $staff
     * @return \Illuminate\Http\Response
     */
    public function show(Staff $staff)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Staff  $staff
     * @return \Illuminate\Http\Response
     */
    public function edit(Staff $staff)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Staff  $staff
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Staff $staff)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Staff  $staff
     * @return \Illuminate\Http\Response
     */
    public function destroy(Staff $staff)
    {
        //
    }
}

resources/views/staffs/index.blade.php
@extends('layouts.dashboard')

@section('css')
<link rel="stylesheet" href="{{ asset('vendor/datatables/datatables.min.css') }}" type="text/css"/>
<link rel="stylesheet" href="{{ asset('vendor/datatables/DataTables-1.10.13/css/dataTables.bootstrap4.min.css') }}" type="text/css"/>
@endsection

@section('content')
{{-- <section class="content"> --}}
<div class="row">
    <div class="col-xs-12">
        <h4>
            <span class="text-uppercase">@lang('staffs.title')</span>
            <a href="{{ route('staffs.create') }}" class="btn btn-primary btn-sm pull-right">
                <i class="fa fa-fw icon-plus"></i> New @lang('title')
            </a>
        </h4>
    </div>
</div>

<div class="animated fadeIn">
    <div class="row">
        <div class="col-xs-12">
            <div class=x_panel>
                <div class=x_content>
                    <table class="table table-sm" id="staffs-table" data-url="{{ route('staffs.datatables') }}" data-token="{{ csrf_token() }}">
                        <thead class="thead-inverse">
                            <tr>
                                <th>@lang('staffs.table.email')</th>
                                <th>@lang('staffs.table.active')</th>
                                <th>@lang('staffs.table.action')</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{{-- </section> --}}
@endsection

@section('js')
<script src="{{ asset('vendor/bootbox/bootbox.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/datatables.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/DataTables-1.10.13/js/dataTables.bootstrap4.min.js') }}"></script>
<script>
    $(document).ready(function() {
        $('#staffs-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: {
                url: $('#staffs-table').data('url'),
                type: "POST",
                headers: {
                    'X-CSRF-TOKEN': $('#staffs-table').data('token')
                }
            },
            columns: [
                {data: 'email', name: 'Name'},
                {data: 'is_active', name: 'Alias'},
                {data: 'action', name: 'Action', sortable: false, searchable: false},
            ],
            language: datatablesLanguage()
          });
    });
</script>
@endsection