routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// -- Authentication Routes
Auth::routes();

// -- BEGIN -- public routes
Route::get('/', function () {
    return view('welcome');
});

Route::get('logout', function () {
    Auth::logout();
    session()->flush();
    return redirect('/');
});

Route::get('home', function () {
    return redirect()->route('dashboard.index');
});
// -- END -- Public routes

// -- BEGIN -- Private route
Route::middleware('auth')->group(function () {
    // -- BEGIN -- Resource route
    Route::resource('dashboard', 'DashboardController', ['only' => ['index']]);
    Route::middleware('RoleAuth:App\User')
        ->resource('users', 'UsersController', ['except' => ['show']]);
    Route::middleware('RoleAuth:App\Module')
        ->resource('modules', 'ModulesController');
    Route::middleware('RoleAuth:App\Staff')
        ->resource('staffs', 'StaffsController');
    Route::middleware('RoleAuth:App\Rolegroup')
        ->resource('rolegroups', 'RolegroupsController', ['except' => ['show']]);
    // -- END -- Resource binding

    // -- BEGIN -- Datatables Specific
    Route::group(['prefix' => 'datatables'], function () {
        Route::post('users', 'DatatablesController@users')
            ->name('datatables.users');
        Route::post('rolegroups', 'DatatablesController@rolegroups')
            ->name('datatables.rolegroups');
        Route::post('modules', 'DatatablesController@modules')
            ->name('datatables.modules');
    });
    // -- END -- Datatables Specific

    // -- BEGIN -- Other API Router
    Route::post('rolegroups/add_modules/{id}', 'RolegroupsController@addModules')
        ->name('rolegroups.addModules');
    Route::post('rolegroups/remove_modules/{id}', 'RolegroupsController@removeModules')
        ->name('rolegroups.removeModules');
    // -- END -- Other API Router
});
// -- END -- Model binding

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Traits\Uuids;
use App\Traits\FlashMessages;

class User extends Authenticatable
{
    use Notifiable, Uuids, FlashMessages;

    public $incrementing = false;

    public $flashDefault = true;

    public $moduleName = 'User';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'email', 'password', 'rolegroup_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $attributes = [
        'is_active' => true,
    ];

    /**
     * One-to-one relation to rolegroup
     *
     * @return \App\Rolegroup instance of Rolegroup
     */
    public function rolegroup()
    {
        return $this->belongsTo('App\Rolegroup');
    }

    /**
     * One-to-one relation to staff
     *
     * @return \App\Staff instance of Staff
     */
    public function staff()
    {
        return $this->hasOne('App\Staff');
    }

    /**
     * One-to-one relation to department
     *
     * @return \App\Department instance of Department
     */
    public function department()
    {
        return $this->belongsToMany('App\Department')->withPivot('position');
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\User;
use App\Staff;
use App\Rolegroup;
use App\Http\Requests\UpdateUserRequest;

use App\Dependencies\CustomBuilder;

use DB;
use Hash;

class UsersController extends Controller
{
    /**
     * Display a listing of the users.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(CustomBuilder $builder)
    {
        $html = $builder
            ->parameters()
            ->ajax([
                'url' => route('datatables.users'),
            ])
            ->columns([
                ['data' => 'email',     'title' => trans('datatables.header.email')],
                ['data' => 'is_active', 'title' => trans('datatables.header.active')],
            ])
            ->addAction();
        return view('users.index')->with(compact('html'));
    }

    /**
     * Show the form for creating a new users.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $staffs = Staff::where(DB::raw('user_id IS NOT NULL'))->get();
        $rolegroups = Rolegroup::notSuper()->get();
        return view('users.form')->with([
            'staffs' => ['' => 'Create New Profile'], $staffs->pluck('name', 'id')->toArray(),
            'rolegroups' => $rolegroups->pluck('rolegroup_name', 'id'),
        ]);
    }

    /**
     * Store a newly created users in storage.
     *
     * @param  \App\Http\Requests\UpdateUserRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UpdateUserRequest $request)
    {
        DB::transaction(function () use ($request) {
            // create new User
            $user = new User();
            $user->fill($request->only(['email', 'password']));
            $user->rolegroup_id = $request->input('rolegroup.id');
            $user->password = Hash::make($user->password);
            $user->save();

            // create new staff and associate to already created user
            $staff = new Staff($request->input('staff'));
            $staff->user()->associate($user);
            $staff->save();
        });
        return redirect()->route('users.index');
    }

    /**
     * Display the specified users.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        // return view('users.show')->with('module', $user);
    }

    /**
     * Show the form for editing the specified users.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $user->load(['rolegroup', 'staff']);

        $staffs = Staff::where(DB::raw('user_id IS NOT NULL'))->get();
        $rolegroups = Rolegroup::notSuper()->get();
        return view('users.form')->with([
            'user' => $user,
            'staffs' => ['' => 'Create New Profile'], $staffs->pluck('name', 'id')->toArray(),
            'rolegroups' => $rolegroups->pluck('rolegroup_name', 'id'),
            ]);
    }

    /**
     * Update the specified users in storage.
     *
     * @param  \App\Http\Requests\UpdateUserRequest  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserRequest $request, User $user)
    {
        $user = DB::transaction(function () use ($request, $user) {
            // autofill user
            $user->fill($request->only('email', 'password'));

            // check for password
            if (empty($user->password)) {
                unset($user->password);
            } else {
                $user->password = Hash::make($user->password);
            }

            // fill relation id
            if ($user->rolegroup->rolegroup_depth > 0) {
                $user->rolegroup_id = $request->input('rolegroup.id');
            }
            $user->save();

            // update child
            $user->staff->update($request->input('staff'));
            return $user;
        });
        return redirect()->route('users.edit', $user->id);
    }

    /**
     * Remove the specified users from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        DB::transaction(function () use ($user) {
            $user->delete();
        });
        return redirect()->route('users.index');
    }
}

resources/views/users/form.blade.php
@extends('layouts.dashboard')

@section('css')
{!! Layouts::usePlugin('select2', 'css') !!}
@endsection

@section('breadcrumbs')
<li class="breadcrumb-item"><a href="{{ route('users.index') }}">Users</a></li>
<li class="breadcrumb-item"><a href="{{ $isEdit ? route('users.edit', $user->id) : route('users.create') }}">{{ $isEdit ? "Edit " : "New " }}</a></li>
@endsection

@section('content')
<section class="content">
    <div class="row m-b-sm">
        <div class="col-xs-6">
            <h4>
                {{ $isEdit ? "EDIT" : "CREATE NEW" }} <span class="text-uppercase">@choice('users.title', 1)</span>
            </h4>
        </div>
        @if ($isEdit)
        <div class="col-xs-6">
            {!! Form::open(['url' => route('users.destroy', $user->id), 'method'=>'delete' ,]) !!}
                <a
                    href="#"
                    data-confirm="Are you sure to delete this resources?"
                    class="btn btn-danger btn-md pull-right js-delete-confirm"
                    ><i class="icon-trash"></i> Delete
                    </a>
            {!! Form::close() !!}
        </div>
        @endif
    </div>
    <div class="row">
        <div class="col-xs-12">
            @if ($isEdit)
                {!! Form::model($user, ['route' => ['users.update', $user->id], 'method' => 'put', 'class' => 'parsley-validate']) !!}
                {!! Form::hidden('isEdit', true) !!}
            @else
                {!! Form::open(['route' => ['users.store'], 'method' => 'post', 'class' => 'parsley-validate']) !!}
            @endif
            <div class=x_panel>
                <div class=x_title>
                    <strong>@choice('users.title', 1) Properties</strong>
                    <small>Form</small>
                </div>
                <div class=x_content>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                                {!! Form::label('email', 'Email', ['class' => 'form-control-label']) !!}
                                {!! Form::email('email', null,
                                    [
                                    'class' => 'form-control',
                                    'data-parsley-required',
                                    'data-parsley-email',
                                    'autocomplete' => 'off'
                                    ]) !!}
                            </div>
                            <div class="form-group">
                                {!! Form::label('password', "Password", ['class' => 'form-control-label']) !!}
                                {!! Form::password('password',
                                    [
                                    'class' => 'form-control',
                                    $isEdit ? '' : 'data-parsley-required',
                                    'minlength' => '8',
                                    'maxlength' => '36',
                                    'autocomplete' => 'off'
                                    ]) !!}
                            </div>
                            @if ($isEdit)
                                @if ($user->rolegroup->rolegroup_depth > 0 )
                                <div class="form-group">
                                    {!! Form::label('rolegroup[id]', "Rolegroup", ['class' => 'form-control-label']) !!}
                                    {!! Form::select('rolegroup[id]', $rolegroups, null,
                                        [
                                        'class' => 'form-control select2',
                                        'data-parsley-required',
                                        'minlength' => '8',
                                        'maxlength' => '36',
                                        'autocomplete' => 'off'
                                        ]) !!}
                                </div>
                                @else
                                    {!! Form::hidden('rolegroup[id]', $user->rolegroup->id) !!}
                                @endif
                            @else
                                <div class="form-group">
                                    {!! Form::label('rolegroup[id]', "Rolegroup", ['class' => 'form-control-label']) !!}
                                    {!! Form::select('rolegroup[id]', $rolegroups, null,
                                        [
                                        'class' => 'form-control select2',
                                        'data-parsley-required',
                                        'minlength' => '8',
                                        'maxlength' => '36',
                                        'autocomplete' => 'off'
                                        ]) !!}
                                </div>
                            @endif
                        </div>
                    </div>
                </div>
            </div>

            <div class=x_panel>
                <div class=x_title>
                    <strong>@choice('staffs.title', 1) Properties</strong>
                    <small>Form</small>
                </div>
                <div class=x_content>
                    @if (! $isEdit)
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="form-group">
                                    {!! Form::label('staff[id]', 'Profile', ['class' => 'form-control-label']) !!}
                                    {!! Form::select('staff[id]', $staffs, null,
                                        [
                                        'class' => 'form-control select2',
                                        ]) !!}
                                </div>
                            </div>
                        </div>
                    <div class="line line-dashed line-lg pull-in"></div>
                    @endif
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                                {!! Form::label('staff[name]', 'Name', ['class' => 'form-control-label']) !!}
                                {!! Form::text('staff[name]', null,
                                    [
                                    'class' => 'form-control',
                                    'data-parsley-required',

                                    ]) !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <button type="submit" class="btn btn-md btn-primary"><i class="fa fa-dot-circle-o"></i> Submit</button>
            <button type="reset" class="btn btn-md btn-danger"><i class="fa fa-ban"></i> Reset</button>
            @if ($isEdit)
                <a href="{{ route('users.index') }}" type="button" class="btn btn-md btn-secondary"><i class="fa fa-arrow-left"></i> Back</a>
            @endif
            {!! Form::close() !!}
        </div>
    </div>
</section>
@endsection

@section('js')
{!! Layouts::usePlugin('select2', 'js') !!}
{!! Layouts::usePlugin('parsley', 'js') !!}
@endsection

resources/views/users/index.blade.php
@extends('layouts.dashboard')

@section('css')
    {!! Layouts::usePlugin('datatables', 'css') !!}
@endsection

@section('breadcrumbs')
<li class="breadcrumb-item"><a href="{{ route('users.index') }}">Users</a></li>
@endsection

@section('content')
    @component('layouts.components.datatables')
        @slot('title')
            @choice('users.title', 2)
        @endslot

        @slot('topButton')
            @can('create', 'App\User')
                <a href="{{ route('users.create') }}" class="btn btn-primary btn-sm pull-right">
                    <i class="fa fa-fw fa-user"></i> New @choice('users.title', 1)
                </a>
            @endcan
        @endslot

        @slot('table')
            {!! $html->table(['style' => 'width:100%;']) !!}
        @endslot

    @endcomponent
@endsection

@push('js')
    {!! Layouts::usePlugin('datatables', 'js') !!}
    {!! $html->scripts() !!}
@endpush