routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// -- Authentication Routes
Auth::routes();

// -- BEGIN -- public routes
Route::get('/', function () {
    return view('welcome');
});

Route::get('logout', function () {
    Auth::logout();
    session()->flush();
    return redirect('/');
});

Route::get('home', function () {
    return redirect()->route('dashboard.index');
});
// -- END -- Public routes

// -- BEGIN -- Private route
Route::middleware('auth')->group(function () {
    // -- BEGIN -- Resource route
    Route::resource('dashboard', 'DashboardController', ['only' => ['index']]);
    Route::middleware('RoleAuth:App\User')
        ->resource('users', 'UsersController', ['except' => ['show']]);
    Route::middleware('RoleAuth:App\Module')
        ->resource('modules', 'ModulesController');
    Route::middleware('RoleAuth:App\Staff')
        ->resource('staffs', 'StaffsController');
    Route::middleware('RoleAuth:App\Rolegroup')
        ->resource('rolegroups', 'RolegroupsController', ['except' => ['show']]);
    // -- END -- Resource binding

    // -- BEGIN -- Datatables Specific
    Route::group(['prefix' => 'datatables'], function () {
        Route::post('users', 'DatatablesController@users')
            ->name('datatables.users');
        Route::post('rolegroups', 'DatatablesController@rolegroups')
            ->name('datatables.rolegroups');
        Route::post('modules', 'DatatablesController@modules')
            ->name('datatables.modules');
    });
    // -- END -- Datatables Specific

    // -- BEGIN -- Other API Router
    Route::post('rolegroups/add_modules/{id}', 'RolegroupsController@addModules')
        ->name('rolegroups.addModules');
    Route::post('rolegroups/remove_modules/{id}', 'RolegroupsController@removeModules')
        ->name('rolegroups.removeModules');
    // -- END -- Other API Router
});
// -- END -- Model binding

app/Rolegroup.php
<?php

namespace App;

use App\BaseModel as Model;

class Rolegroup extends Model
{
    /**
     * Fillable column
     *
     * @var array
     */
    protected $fillable = ['rolegroup_name', 'rolegroup_depth'];

    public function getRolesStructure($rgId)
    {
        $roles      = Role::where('rolegroup_id', $rgId)->get();
        $roleCooked = [];
        $roleServe  = [];

        foreach ($roles as $role) {
            if (! isset($roleCooked['mod_' . $role->module_id])) {
                $roleCooked['mod_' . $role->module_id] = [
                    'module_id' => $role->module_id,
                    'abilities' => [$role->role_ability]
                ];
            } else {
                array_push($roleCooked['mod_' . $role->module_id]['abilities'], $role->role_ability);
            }
        }

        foreach ($roleCooked as $cooked) {
            array_push($roleServe, $cooked);
        }

        return $roleServe;
    }

    /**
     * Initial relations one to many with users table
     *
     * @return \App\User instance of User;
     */
    public function users()
    {
        return $this->hasMany('App\User');
    }

    /**
     * Initial relations one to many with roles table
     *
     * @return \App\Role instance of Role;
     */
    public function roles()
    {
        return $this->hasMany('App\Role');
    }

    /**
     * Default scope if not super admin
     *
     * @return Instance of query builder
     */
    public function scopeNotSuper()
    {
        return $this->where('rolegroup_depth', ">", 0);
    }
}

app/Http/Controllers/RolegroupsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Collection;

use App\Rolegroup;
use App\Module;
use App\Role;
use App\Helper\Flash;
use App\Http\Requests\UpdateRolegroupRequest;

use App\Dependencies\CustomBuilder;

use Datatables;
use Form;
use DB;

class RolegroupsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(CustomBuilder $builder)
    {
        $html = $builder
            ->parameters()
            ->ajax([
                'url' => route('datatables.rolegroups'),
            ])
            ->columns([
                ['data' => 'rolegroup_name',     'title' => trans('datatables.header.name')],
                ['data' => 'members', 'title' => trans('datatables.header.members')],
                ['data' => 'level', 'title' => trans('datatables.header.level')],
            ])
            ->addAction();
        return view('rolegroups.index')->with(compact('html'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('rolegroups.form')->with([
            'modules' => Module::all()
            ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\UpdateRolegroupRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UpdateRolegroupRequest $request)
    {
        $rolegroup = DB::transaction(function () use ($request) {
            $rolegroup = Rolegroup::create($request->all());
            return $rolegroup;
        });

        return redirect()->route('rolegroups.edit', $rolegroup->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Rolegroup $rolegroup
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Rolegroup $rolegroup
     * @return \Illuminate\Http\Response
     */
    public function edit(Rolegroup $rolegroup)
    {
        $modules = Module::all()->pluck('module_name', 'id');
        $rolegroup->load(['roles', 'roles.module']);
        $abilities = [
            'XREAD' => 'XREAD',
            'XCREATE' => 'XCREATE',
            'XUPDATE' => 'XUPDATE',
            'XDELETE' => 'XDELETE',
            'READ' => 'READ',
            'CREATE' => 'CREATE',
            'UPDATE' => 'UPDATE',
            'DELETE' => 'DELETE',
        ];
        $roles = [];
        foreach ($rolegroup->roles as $role) {
            $roles[$role->module_id][] = $role;
        }
        $roles = collect($roles);

        return view('rolegroups.form')->with([
            'rolegroup' => $rolegroup,
            'modules' => $modules,
            'abilities' => $abilities,
            'rolesCooked' => $roles,
            ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateRolegroupRequest  $request
     * @param  \App\Rolegroup $rolegroup
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRolegroupRequest $request, Rolegroup $rolegroup)
    {
        DB::transaction(function () use ($request, $rolegroup) {
            $rolegroup->fill($request->only(['rolegroup_name', 'rolegroup_depth']));
            $rolegroup->save();

            Role::where('rolegroup_id', $rolegroup->id)->delete();
            foreach ($request->abilities as $module_id => $role_abilities) {
                foreach ($role_abilities as $role_ability) {
                    $role = new Role();
                    $role->fill([
                        'rolegroup_id' => $rolegroup->id,
                        'module_id' => $module_id,
                        'role_ability' => $role_ability,
                        ]);
                    $role->save();
                }
            }
        });
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Rolegroup $rolegroup
     * @return \Illuminate\Http\Response
     */
    public function destroy(Rolegroup $rolegroup)
    {
        DB::transaction(function () use ($rolegroup) {
            $rolegroup->delete();
        });
        return redirect()->route('rolegroups.index');
    }

    /**
     * Add modules to current rolegroup
     *
     * @param Request $request contain deleted module request
     * @param uuid  $id      Module ID
     */
    public function addModules(Request $request, $id)
    {
        $response = ['status' => false];

        $response = DB::transaction(function () use ($request, $id) {
            $roles = Role::all();
            Role::where('module_id', $request->input('module_id'))->where('rolegroup_id', $id)->delete();
            foreach ($request->input('module_id') as $module_id) {
                $role = new Role([
                    'rolegroup_id' => $id,
                    'module_id' => $module_id,
                    'role_ability' => 'READ'
                    ]);
                $role->save();
            }

            Flash::push('success-message', 'Module has been added');
            return ['status' => true];
        });

        return collect($response);
    }

    /**
     * Remove modules from current rolegroup
     *
     * @param Request $request contain request
     * @param uuid  $id      Module ID
     */
    public function removeModules(Request $request, $id)
    {
        $response = ['status' => false];

        $response = DB::transaction(function () use ($request, $id) {
            Role::where('rolegroup_id', $id)->where('module_id', $request->input('module_id'))->delete();
            return ['status' => true];
        });
        return collect($response);
    }
}

resources/views/rolegroups/form.blade.php
@extends('layouts.dashboard')

@section('css')
{!! Layouts::usePlugin('select2', 'css') !!}
@endsection

@section('breadcrumbs')
<li class="breadcrumb-item"><a href="{{ route('rolegroups.index') }}">Rolegroups</a></li>
<li class="breadcrumb-item"><a href="{{ $isEdit ? route('rolegroups.edit', $rolegroup->id) : route('rolegroups.create') }}">{{ $isEdit ? "Edit " : "New " }}</a></li>
@endsection



@section('content')
<section class="content">
    <div class="row m-b-sm">
        <div class="col-xs-6">
            <h4>
                {{ $isEdit ? "EDIT" : "CREATE NEW" }} <span class="text-uppercase">@choice('rolegroups.title', 1)</span>
            </h4>
        </div>
        @if ($isEdit)
        @can('delete', $rolegroup)
            <div class="col-xs-6">
                {!! Form::open(['url' => route('rolegroups.destroy', $rolegroup->id), 'method'=>'delete' ,]) !!}
                    <a
                        href="#"
                        data-confirm="Are you sure to delete this resources?"
                        class="btn btn-danger btn-md pull-right js-delete-confirm"
                        ><i class="fa fa-trash-o"></i> Delete
                        </a>
                {!! Form::close() !!}
            </div>
        @endcan
        @endif
    </div>
    <div class="row">
        <div class="col-xs-12">
            @if ($isEdit)
                {!! Form::model($rolegroup, ['route' => ['rolegroups.update', $rolegroup->id], 'method' => 'put', 'class' => 'parsley-validate']) !!}
                {!! Form::hidden('isEdit', true) !!}
            @else
                {!! Form::open(['route' => ['rolegroups.store'], 'method' => 'post', 'class' => 'parsley-validate']) !!}
            @endif
            <div class=x_panel>
                <div class=x_title>
                    <strong>@choice('rolegroups.title', 1) Properties</strong>
                    <small>Form</small>
                </div>
                <div class=x_content>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                                {!! Form::label('rolegroup_name', trans_choice('rolegroups.title', 1).' name', ['class' => 'form-control-label']) !!}
                                {!! Form::text('rolegroup_name', null,
                                    [
                                    'class' => 'form-control',
                                    'data-parsley-required'
                                    ]) !!}
                            </div>
                            <div class="form-group">
                                {!! Form::label('', trans_choice('rolegroups.title', 1)." level", ['class' => 'form-control-label']) !!}
                                {!! Form::number('rolegroup_depth', null,
                                    [
                                    'class' => 'form-control',
                                    'min' => '0',
                                    'max' => '99',
                                    'data-parsley-required',
                                    ]) !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            @if ($isEdit)
                <div class=x_panel>
                    <div class=x_title>
                        <strong>@choice('rolegroups.title', 1) Abilities</strong>
                        <small>Form</small>
                    </div>
                    <div class=x_content>
                        <div class="row">
                            <div class="col-xs-10">
                                {!! Form::select('addAbilities', $modules->except($rolegroup->roles->pluck('module_id')->toArray()), '', ['id' => 'addAbilities', 'class' => 'form-control select2', 'multiple' => 'multiple']) !!}
                            </div>
                            <div class="col-xs-2">
                                {!! Form::button('<i class="fa fa-plus"></i> Add Module', [
                                    'id' => 'add-module-btn',
                                    'class' => 'btn btn-primary btn-block',
                                    'data-url' => route('rolegroups.addModules', ['id' => $rolegroup->id]),
                                    'data-csrf' => csrf_token() ]) !!}
                            </div>
                        </div>
                        <div class="line line-dashed line-lg pull-in"></div>
                        @foreach ($rolesCooked as $module_id => $roles)
                        <div class="row m-b" id="module_{{ $module_id }}">
                            <div class="col-xs-6">
                                {!! Form::select($module_id, [$roles[0]->module->id => $roles[0]->module->module_name], $roles[0]->module->id, ['class' => 'form-control', 'disabled']) !!}
                            </div>
                            <div class="col-xs-5">
                                {!! Form::select("abilities[".$module_id."][]", $abilities, collect($roles)->pluck('role_ability')->toArray(), ['class' => 'form-control select2', 'multiple']) !!}
                            </div>
                            <div class="col-xs-1">
                                {!! Form::button('<i class="fa fa-trash-o"></i>', [
                                    'id' => 'add-module-btn',
                                    'class' => 'btn btn-block btn-danger btn-delete',
                                    'data-url' => route('rolegroups.removeModules', ['id' => $rolegroup->id]),
                                    'data-csrf' => csrf_token(),
                                    "data-module-name" => $roles[0]->module->module_name,
                                    "data-module-id" => $roles[0]->module->id ]) !!}
                            </div>
                        </div>
                        @endforeach

                    </div>
                </div>
            @endif

            <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i> Submit</button>
            <button type="reset" class="btn btn-sm btn-danger"><i class="fa fa-ban"></i> Reset</button>

            {!! Form::close() !!}
        </div>
    </div>
</section>
@endsection

@push('js')
{!! Layouts::usePlugin('select2', 'js') !!}
{!! Layouts::usePlugin('parsley', 'js') !!}

<script>
    $(document).ready(function() {
        $('#add-module-btn').click(function(event) {
            event.preventDefault();

            var
                url = $(this).data('url');
                data = {
                    module_id: $('select').val(),
                    _token: $(this).data('csrf')
                }
            $.post(url, data, function(data) {
                if (data.status) {
                    location.reload();
                }
            });
        });

        $(".btn-delete").click(function(event) {
            event.preventDefault();
            var
                url = $(this).data('url')
                moduleName = $(this).data('module-name')
                moduleId = $(this).data('module-id')
                data = {
                    module_id: moduleId,
                    _token: $(this).data('csrf')
                }
            $.post(url, data, function(data, textStatus, xhr) {
                if (data.status) {
                    $('#module_'+moduleId).remove();
                    $('#addAbilities')
                        .append($("<option></option>")
                        .attr("value", moduleId)
                        .text(moduleName))
                        .select2();
                }
            });
        });

    });
</script>
@endpush

resources/views/rolegroups/index.blade.php
@extends('layouts.dashboard')

@section('css')
    {!! Layouts::usePlugin('datatables', 'css') !!}
@endsection

@section('breadcrumbs')
<li class="breadcrumb-item"><a href="{{ route('rolegroups.index') }}">Rolegroups</a></li>
@endsection

@section('content')
    @component('layouts.components.datatables')
        @slot('title')
            @choice('rolegroups.title', 2)
        @endslot

        @slot('topButton')
            @can('create', 'App\Rolegroup')
                <a href="{{ route('rolegroups.create') }}" class="btn btn-primary btn-md pull-right">
                    <i class="fa fa-fw fa-user-plus"></i> New @choice('rolegroups.title', 1)
                </a>
            @endcan
        @endslot

        @slot('table')
            {!! $html->table(['style' => 'width:100%;']) !!}
        @endslot

    @endcomponent
@endsection

@push('js')
    {!! Layouts::usePlugin('datatables', 'js') !!}
    {!! $html->scripts() !!}
@endpush