routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// -- Authentication Routes
Auth::routes();

// -- BEGIN -- public routes
Route::get('/', function () {
    return view('welcome');
});

Route::get('logout', function () {
    Auth::logout();
    session()->flush();
    return redirect('/');
});

Route::get('home', function () {
    return redirect()->route('dashboard.index');
});
// -- END -- Public routes

// -- BEGIN -- Private route
Route::middleware('auth')->group(function () {
    // -- BEGIN -- Resource route
    Route::resource('dashboard', 'DashboardController', ['only' => ['index']]);
    Route::middleware('RoleAuth:App\User')
        ->resource('users', 'UsersController', ['except' => ['show']]);
    Route::middleware('RoleAuth:App\Module')
        ->resource('modules', 'ModulesController');
    Route::middleware('RoleAuth:App\Staff')
        ->resource('staffs', 'StaffsController');
    Route::middleware('RoleAuth:App\Rolegroup')
        ->resource('rolegroups', 'RolegroupsController', ['except' => ['show']]);
    // -- END -- Resource binding

    // -- BEGIN -- Datatables Specific
    Route::group(['prefix' => 'datatables'], function () {
        Route::post('users', 'DatatablesController@users')
            ->name('datatables.users');
        Route::post('rolegroups', 'DatatablesController@rolegroups')
            ->name('datatables.rolegroups');
        Route::post('modules', 'DatatablesController@modules')
            ->name('datatables.modules');
    });
    // -- END -- Datatables Specific

    // -- BEGIN -- Other API Router
    Route::post('rolegroups/add_modules/{id}', 'RolegroupsController@addModules')
        ->name('rolegroups.addModules');
    Route::post('rolegroups/remove_modules/{id}', 'RolegroupsController@removeModules')
        ->name('rolegroups.removeModules');
    // -- END -- Other API Router
});
// -- END -- Model binding

app/Module.php
<?php

namespace App;

use App\BaseModel as Model;

class Module extends Model
{
    protected $fillable = [
        'module_alias',
        'module_name',
        'module_core',
        'locked',
    ];

    /**
     * One-to-many relation to roles
     *
     * @return \App\Roles intance of Roles;
     */
    public function roles()
    {
        return $this->hasMany('App\Role');
    }
}

app/Http/Controllers/ModulesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests\UpdateModuleRequest;
use App\Module;

use App\Dependencies\CustomBuilder;

use Datatables;
use Form;
use DB;
use App\Helper\Flash;

class ModulesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(CustomBuilder $builder)
    {
        $html = $builder
            ->parameters()
            ->ajax([
                'url' => route('datatables.modules'),
            ])
            ->columns([
                ['data' => 'module_name',     'title' => trans('datatables.header.name')],
                ['data' => 'module_alias', 'title' => trans('datatables.header.alias')],
                ['data' => 'locked', 'title' => trans('datatables.header.locked')],
            ])
            ->addAction();
        return view('modules.index')->with(compact('html'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('modules.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\UpdateModuleRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UpdateModuleRequest $request)
    {
        $module = DB::transaction(function () use ($request) {
            $module = Module::create($request->all());
            return $module;
        });
        return redirect()->route('modules.show', $module->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Module  $module
     * @return \Illuminate\Http\Response
     */
    public function show(Module $module)
    {
        return view('modules.show')->with('module', $module);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Module  $module
     * @return \Illuminate\Http\Response
     */
    public function edit(Module $module)
    {
        return view('modules.form')->with('module', $module);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\UpdateModuleRequest  $request
     * @param  \App\Module  $module
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateModuleRequest $request, Module $module)
    {
        $module = DB::transaction(function () use ($module, $request) {
            $module->update($request->except('module_alias'));
            return $module;
        });
        return redirect()->route('modules.show', $module->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Module  $module
     * @return \Illuminate\Http\Response
     */
    public function destroy(Module $module)
    {
        if ($module->locked) {
            Flash::push('error-message', trans('modules.delete_locked'));
            return redirect()->route('modules.index');
        }

        DB::transaction(function () use ($module) {
            $module->delete();
        });
        return redirect()->back();
    }
}

resources/views/modules/form.blade.php
@extends('layouts.dashboard')

@section('css')
@endsection

@section('breadcrumbs')
<li class="breadcrumb-item"><a href="{{ route('modules.index') }}">Modules</a></li>
<li class="breadcrumb-item"><a href="{{ $isEdit ? route('modules.edit', $module->id) : route('modules.create') }}">{{ $isEdit ? "Edit " : "New " }}</a></li>
@endsection

@section('content')
<section class="content">
    <h4>{{ $isEdit ? "EDIT" : "CREATE NEW" }} MODULE</h4>
    <div class="row">
        <div class="col-xs-12 col-md-6">
            @if ($isEdit)
                {!! Form::model($module, ['route' => ['modules.update', $module->id], 'method' => 'put']) !!}
                {!! Form::hidden('isEdit', true) !!}
            @else
                {!! Form::open(['route' => ['modules.store'], 'method' => 'post']) !!}
            @endif
            <div class=x_panel>
                <div class=x_title>
                    <strong>Module Properties</strong>
                    <small>Form</small>
                </div>
                <div class=x_content>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group form-float">
                                {!! Form::label('', 'Module name', ['class' => 'form-label']) !!}
                                {!! Form::text('module_name', null, ['class' => 'form-control', 'placeholder' => 'Module Name']) !!}
                            </div>
                            <div class="form-group form-float">
                                {!! Form::label('', "Module Alias", ['class' => 'form-label']) !!}
                                {!! Form::text('module_alias', null, ['class' => 'form-control', $isEdit ? 'disabled' : '', 'placeholder' => 'modulealias']) !!}
                            </div>
                            <div class="form-check">
                                <label class="form-check-label">
                                    {!! Form::hidden('module_core', 0) !!}
                                    {!! Form::checkbox('module_core', true, null, ['class' => 'form-check-input']) !!}
                                    &nbsp;Core
                                </label>
                            </div>
                            <div class="form-check">
                                <label class="form-check-label">
                                    {!! Form::hidden('locked', 0) !!}
                                    {!! Form::checkbox('locked', true, null, ['class' => 'form-check-input']) !!}
                                    &nbsp;Locked
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i> Submit</button>
                    <button type="reset" class="btn btn-sm btn-danger"><i class="fa fa-ban"></i> Reset</button>
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
</section>
@endsection

@section('js')
@endsection

resources/views/modules/index.blade.php
@extends('layouts.dashboard')

@section('css')
    {!! Layouts::usePlugin('datatables', 'css') !!}
@endsection

@section('breadcrumbs')
<li class="breadcrumb-item"><a href="{{ route('modules.index') }}">Modules</a></li>
@endsection

@section('content')
    @component('layouts.components.datatables')
        @slot('title')
            @choice('rolegroups.title', 2)
        @endslot

        @slot('topButton')
            @can('create', 'App\Module')
                <a href="{{ route('modules.create') }}" class="btn btn-primary btn-md pull-right">
                    <i class="fa fa-fw fa-user-plus"></i> New @choice('modules.title', 1)
                </a>
            @endcan
        @endslot

        @slot('table')
            {!! $html->table(['style' => 'width:100%;']) !!}
        @endslot

    @endcomponent
@endsection

@push('js')
    {!! Layouts::usePlugin('datatables', 'js') !!}
    {!! $html->scripts() !!}
@endpush

resources/views/modules/show.blade.php
@extends('layouts.dashboard')

@section('css')
@endsection

@section('breadcrumbs')
<li class="breadcrumb-item"><a href="{{ route('modules.index') }}">Modules</a></li>
<li class="breadcrumb-item"><a href="{{ route('modules.show', $module->id) }}">View</a></li>
@endsection

@section('content')
<section class="content">
    <h4>MODULE</h4>
    <div class="row">
        <div class="col-xs-12 col-md-6">
            <div class=x_panel>
                <div class=x_title>
                    <strong>Module Properties</strong>
                    <small>Form</small>
                </div>
                <div class=x_content>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                                {!! Form::label('', 'Module name', ['class' => 'form-label']) !!}
                                <p><strong><big>{{ $module->module_name }}</big></strong></p>
                            </div>
                            <div class="form-group">
                                {!! Form::label('', "Module Alias", ['class' => 'form-label']) !!}
                                <p><strong><big>{{ $module->module_alias }}</big></strong></p>
                            </div>
                            <div class="form-group">
                                @if ($module->locked)
                                    <span class="badge badge-danger">locked</span>
                                @else
                                    <span class="badge badge-success">unlocked</span>
                                @endif
                                @if ($module->module_core)
                                    <span class="badge badge-success">core</span>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@section('js')
@endsection